// PM2 ecosystem untuk TamsHub ClaudProx.
// Catatan: gateway/dist/server.js dihasilkan setelah `pnpm --filter @claudprox/gateway build`.
// Web app pakai `next start` lewat node_modules/next.

module.exports = {
  apps: [
    {
      name: "claudprox-gateway",
      cwd: "./apps/gateway",
      script: "dist/server.js",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_production: {
        NODE_ENV: "production",
        PORT: "4015",
      },
      error_file: "../../logs/gateway-error.log",
      out_file: "../../logs/gateway-out.log",
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "claudprox-web-landing",
      cwd: "./apps/web-landing",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 4016",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_production: {
        NODE_ENV: "production",
        PORT: "4016",
      },
      error_file: "../../logs/web-landing-error.log",
      out_file: "../../logs/web-landing-out.log",
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "claudprox-web-dashboard",
      cwd: "./apps/web-dashboard",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 4017",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_production: {
        NODE_ENV: "production",
        PORT: "4017",
      },
      error_file: "../../logs/web-dashboard-error.log",
      out_file: "../../logs/web-dashboard-out.log",
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "claudprox-web-admin",
      cwd: "./apps/web-admin",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 4018",
      interpreter: "node",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_production: {
        NODE_ENV: "production",
        PORT: "4018",
      },
      error_file: "../../logs/web-admin-error.log",
      out_file: "../../logs/web-admin-out.log",
      time: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
